using Microsoft.Xna.Framework;

namespace InvisibleHand.Rules
{
    /// Interface that merely serves as a shallow outline of the properties available on a Item object
    public abstract class IItem
    {
		public const int flaskTime = 72000;
		public const int copper = 1;
		public const int silver = 100;
		public const int gold = 10000;
		public const int platinum = 1000000;
		public const int maxPrefixes = 84;
		public static int potionDelay = 3600;
		public static int restorationDelay = 3000;
		public bool questItem;
		public static int[] headType = new int[194];
		public static int[] bodyType = new int[195];
		public static int[] legType = new int[135];
		public static bool[] staff = new bool[3602];
		public static bool[] claw = new bool[3602];
		public bool flame;
		public bool mech;
		public int noGrabDelay;
		public bool beingGrabbed;
		public bool isBeingGrabbed;
		public int spawnTime;
		public int tileWand = -1;
		public bool wornArmor;
		public byte dye;
		public int fishingPole = 1;
		public int bait;
		public static int coinGrabRange = 350;
		public static int manaGrabRange = 300;
		public static int lifeGrabRange = 250;
		public short makeNPC;
		public bool expertOnly;
		public bool expert;
		public short hairDye = -1;
		public byte paint;
		public bool instanced;
		public int ownIgnore = -1;
		public int ownTime;
		public int keepTime;
		public int type;
		public bool favorited;
		public int holdStyle;
		public int useStyle;
		public bool channel;
		public bool accessory;
		public int useAnimation;
		public int useTime;
		public int stack;
		public int maxStack;
		public int pick;
		public int axe;
		public int hammer;
		public int tileBoost;
		public int createTile = -1;
		public int createWall = -1;
		public int placeStyle;
		public int damage;
		public float knockBack;
		public int healLife;
		public int healMana;
		public bool potion;
		public bool consumable;
		public bool autoReuse;
		public bool useTurn;
		public Color color;
		public int alpha;
		public short glowMask;
		public float scale = 1f;
		public int useSound;
		public int defense;
		public int headSlot = -1;
		public int bodySlot = -1;
		public int legSlot = -1;
		public sbyte handOnSlot = -1;
		public sbyte handOffSlot = -1;
		public sbyte backSlot = -1;
		public sbyte frontSlot = -1;
		public sbyte shoeSlot = -1;
		public sbyte waistSlot = -1;
		public sbyte wingSlot = -1;
		public sbyte shieldSlot = -1;
		public sbyte neckSlot = -1;
		public sbyte faceSlot = -1;
		public sbyte balloonSlot = -1;
		public int stringColor;
		public string toolTip;
		public string toolTip2;
		public int owner = 255;
		public int rare;
		public int shoot;
		public float shootSpeed;
		public int ammo;
		public bool notAmmo;
		public int useAmmo;
		public int lifeRegen;
		public int manaIncrease;
		public bool buyOnce;
		public int mana;
		public bool noUseGraphic;
		public bool noMelee;
		public int release;
		public int value;
		public bool buy;
		public bool social;
		public bool vanity;
		public bool material;
		public bool noWet;
		public int buffType;
		public int buffTime;
		public int mountType = -1;
		public bool cartTrack;
		public bool uniqueStack;
		public int netID;
		public int crit;
		public byte prefix;
		public bool melee;
		public bool magic;
		public bool ranged;
		public bool thrown;
		public bool summon;
		public int reuseDelay;
		public bool newAndShiny;
    }
}
